language: cpp
compiler:
  - clang
  - gcc

addons:
  ssh_known_hosts: git.bro.org
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bison
      - cmake
      - flex
      - libpcap-dev
      - libssl-dev
      - python-dev
      - swig
      - zlib1g-dev

branches:
  only:
  - master

notifications:
  email:
    recipients:
    - bro-commits-internal@bro.org

before_script: sh .travis.job build

script: sh .travis.job run

after_failure: sh .travis.job failure
